// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApPgQO34UTy57H0YL9bcA6zQl33FOg54',
    appId: '1:35923112741:web:a3d838997b5e3ee646e0cc',
    messagingSenderId: '35923112741',
    projectId: 'njangi-hub',
    authDomain: 'njangi-hub.firebaseapp.com',
    storageBucket: 'njangi-hub.appspot.com',
    measurementId: 'G-GL3NCPCGTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ZiZv-OWftSvh-0SntnSdEVSDe2PIBSE',
    appId: '1:35923112741:android:e0169d9064c3bf5746e0cc',
    messagingSenderId: '35923112741',
    projectId: 'njangi-hub',
    storageBucket: 'njangi-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJSXeYjyerZMeEO8pxDgFL1ps2PfpYuQ',
    appId: '1:35923112741:ios:b76e0cb9933b57b046e0cc',
    messagingSenderId: '35923112741',
    projectId: 'njangi-hub',
    storageBucket: 'njangi-hub.appspot.com',
    iosBundleId: 'com.lespa.njangihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJSXeYjyerZMeEO8pxDgFL1ps2PfpYuQ',
    appId: '1:35923112741:ios:db905a1ded5c095346e0cc',
    messagingSenderId: '35923112741',
    projectId: 'njangi-hub',
    storageBucket: 'njangi-hub.appspot.com',
    iosBundleId: 'com.example.njangiHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAApPgQO34UTy57H0YL9bcA6zQl33FOg54',
    appId: '1:35923112741:web:d03a9b505a33e63f46e0cc',
    messagingSenderId: '35923112741',
    projectId: 'njangi-hub',
    authDomain: 'njangi-hub.firebaseapp.com',
    storageBucket: 'njangi-hub.appspot.com',
    measurementId: 'G-EBZ7KFCWE3',
  );

}