///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesBlackGroup = 'assets/images/black_group.jpg';
  static const String imagesBlackGroup2 = 'assets/images/black_group_2.jpg';
  static const String imagesBlackMan = 'assets/images/black_man.jpg';
  static const String imagesCube = 'assets/images/cube.png';
  static const String imagesGradient1TopLeft = 'assets/images/Gradient1TopLeft.png';
  static const String imagesLauncherIcon = 'assets/images/launcher-icon.png';
  static const String imagesLogo1 = 'assets/images/logo1.png';
  static const String imagesLogoIcon = 'assets/images/logo-icon.png';
  static const String imagesLogoOnly = 'assets/images/logo-only.png';
  static const String imagesLogoVertical = 'assets/images/logo-vertical.png';
  static const String imagesPolygon05 = 'assets/images/Polygon05.png';
  static const String imagesUser = 'assets/images/user.png';

}
